"""make_segment_budget_problem_nullable_for_chat_leads

Revision ID: 4005d0fbdbb2
Revises: af20881a8b50
Create Date: 2026-02-16 07:26:50.554001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4005d0fbdbb2'
down_revision: Union[str, Sequence[str], None] = 'af20881a8b50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('appointments', 'client_id',
               existing_type=sa.UUID(),
               nullable=False,
               existing_comment='Cliente que agendou a reunião')
    op.alter_column('clients', 'segment',
               existing_type=postgresql.ENUM('CLINICA_MEDICA', 'CLINICA_ODONTOLOGICA', 'CLINICA_ESTETICA', 'LABORATORIO', 'HOSPITAL', 'MEDICO_AUTONOMO', 'DENTISTA_AUTONOMO', 'PSICOLOGO', 'FISIOTERAPEUTA', 'NUTRICIONISTA', 'FARMACIA', 'ECOMMERCE_SAUDE', 'EQUIPAMENTOS_MEDICOS', 'PLANO_SAUDE', 'OUTRO', name='clientsegment'),
               nullable=True,
               comment='Segmento de atuação (foco em saúde). Nullable para leads via chat.',
               existing_comment='Segmento de atuação (foco em saúde)')
    op.alter_column('clients', 'monthly_budget',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True,
               comment='Orçamento mensal disponível para marketing (R$). Nullable para leads via chat.',
               existing_comment='Orçamento mensal disponível para marketing (R$)')
    op.alter_column('clients', 'main_marketing_problem',
               existing_type=sa.TEXT(),
               nullable=True,
               comment='Principal problema/desafio de marketing atual. Nullable para leads via chat.',
               existing_comment='Principal problema/desafio de marketing atual')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('clients', 'main_marketing_problem',
               existing_type=sa.TEXT(),
               nullable=False,
               comment='Principal problema/desafio de marketing atual',
               existing_comment='Principal problema/desafio de marketing atual. Nullable para leads via chat.')
    op.alter_column('clients', 'monthly_budget',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False,
               comment='Orçamento mensal disponível para marketing (R$)',
               existing_comment='Orçamento mensal disponível para marketing (R$). Nullable para leads via chat.')
    op.alter_column('clients', 'segment',
               existing_type=postgresql.ENUM('CLINICA_MEDICA', 'CLINICA_ODONTOLOGICA', 'CLINICA_ESTETICA', 'LABORATORIO', 'HOSPITAL', 'MEDICO_AUTONOMO', 'DENTISTA_AUTONOMO', 'PSICOLOGO', 'FISIOTERAPEUTA', 'NUTRICIONISTA', 'FARMACIA', 'ECOMMERCE_SAUDE', 'EQUIPAMENTOS_MEDICOS', 'PLANO_SAUDE', 'OUTRO', name='clientsegment'),
               nullable=False,
               comment='Segmento de atuação (foco em saúde)',
               existing_comment='Segmento de atuação (foco em saúde). Nullable para leads via chat.')
    op.alter_column('appointments', 'client_id',
               existing_type=sa.UUID(),
               nullable=True,
               existing_comment='Cliente que agendou a reunião')
    # ### end Alembic commands ###
