"""initial_marketing_crm

Revision ID: e76a85ad1fc9
Revises: 
Create Date: 2026-01-13 22:26:15.565454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e76a85ad1fc9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False, comment='Primeiro nome do cliente'),
    sa.Column('last_name', sa.String(length=100), nullable=False, comment='Sobrenome do cliente'),
    sa.Column('phone', sa.String(length=20), nullable=False, comment='Telefone/WhatsApp (identificador único)'),
    sa.Column('email', sa.String(length=255), nullable=True, comment='Email de contato'),
    sa.Column('company_name', sa.String(length=255), nullable=True, comment='Nome da empresa (opcional para autônomos PF)'),
    sa.Column('segment', sa.Enum('CLINICA_MEDICA', 'CLINICA_ODONTOLOGICA', 'CLINICA_ESTETICA', 'LABORATORIO', 'HOSPITAL', 'MEDICO_AUTONOMO', 'DENTISTA_AUTONOMO', 'PSICOLOGO', 'FISIOTERAPEUTA', 'NUTRICIONISTA', 'FARMACIA', 'ECOMMERCE_SAUDE', 'EQUIPAMENTOS_MEDICOS', 'PLANO_SAUDE', 'OUTRO', name='clientsegment'), nullable=False, comment='Segmento de atuação (foco em saúde)'),
    sa.Column('monthly_budget', sa.Numeric(precision=10, scale=2), nullable=False, comment='Orçamento mensal disponível para marketing (R$)'),
    sa.Column('main_marketing_problem', sa.Text(), nullable=False, comment='Principal problema/desafio de marketing atual'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Anotações adicionais sobre o cliente'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_phone'), 'clients', ['phone'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False, comment='Email de login (único)'),
    sa.Column('hashed_password', sa.String(length=255), nullable=False, comment='Senha hasheada (bcrypt)'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Se usuário está ativo no sistema'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('appointments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False, comment='Cliente que agendou a reunião'),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False, comment='Data e hora agendada para a reunião'),
    sa.Column('duration_minutes', sa.Integer(), nullable=False, comment='Duração da reunião em minutos (padrão 60)'),
    sa.Column('meeting_type', sa.String(length=50), nullable=True, comment="Tipo de reunião (ex: 'Inicial', 'Follow-up')"),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'CANCELLED', 'COMPLETED', name='appointmentstatus'), nullable=False, comment='Status atual do agendamento'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Observações sobre a reunião'),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True, comment='Data/hora do cancelamento'),
    sa.Column('cancellation_reason', sa.Text(), nullable=True, comment='Motivo do cancelamento'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conversations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=True),
    sa.Column('channel', sa.Enum('WEB', 'WHATSAPP', 'INSTAGRAM', name='channeltype'), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_message_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ASSISTANT', name='messagerole'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    op.drop_table('conversations')
    op.drop_table('appointments')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_clients_phone'), table_name='clients')
    op.drop_table('clients')
    # ### end Alembic commands ###
